### ISSUE TITLE
how to use packet capture

### ISSUE THREAD

**Issue by pillerthriller** [cisco-system-traffic-generator/trex-java-sdk#11]
Hi,
Im not sure if this should be here because it is not a issue more of a question how to use the packet capture in the sdk. Maybe i should ask this in the google trex group instead?
My problem is that i can't figure out or find any info how to use trex java sdk to get captured packets and do anything with them, this is how far i got:
CapturedPackets captureStream = trex.stopCapture(rxPort, captureId);
List<CapturedPkt> capturedPackets = captureStream.getPkts();
System.out.print("First captured packet origin:" + capturedPackets.get(1).getOrigin());

But i want to see the complete packet and do checks on it like if it had expected vlan header.
How do i accomplish this?

**Comment by kisel** [comment]
Hi,
Java SDK provides a binary packet representation(base64-encoded), which can be parsed by org.pcap4j.packet.EthernetPacket. Here is an example how the GUI retrieves information from the captured packet - using decode and pcap4j parse:
https://github.com/cisco-system-traffic-generator/trex-stateless-gui/blob/master/src/main/java/com/cisco/trex/stl/gui/controllers/capture/MonitorController.java#L360-L372

Once parsed, you can use pcap4j object model to retrieve data(or just check particular packet bytes on the given offset). Let me know if this works for you.

also responded here:  https://groups.google.com/forum/#!msg/trex-tgn/XkvzdtPCVXs/4r7u_QkmAgAJ

**Comment by pillerthriller** [comment]
Thanks for quick answer, i will close this and keep the discussion to the google group
