### ISSUE TITLE
Example of VM usage

### ISSUE THREAD

**Issue by walrusss** [cisco-system-traffic-generator/trex-java-sdk#13]
Hi,
Can you provide a simple example of how to use VM Instruction in Stream using SDK?
Thanks.

**Comment by hedjuo** [comment]
Hi.

It is not implemented yet. You can try to implement it.
[Stream](https://github.com/cisco-system-traffic-generator/trex-java-sdk/blob/8454c7e5366dde1ceb37a291456dc24b79600e3f/src/main/java/com/cisco/trex/stateless/model/Stream.java#L19) object has a property [StreamVM](https://github.com/cisco-system-traffic-generator/trex-java-sdk/blob/693b0d69375c174c8bb166819fb289652b6437da/src/main/java/com/cisco/trex/stateless/model/StreamVM.java#L5) which contains a list of [VMinstruction](https://github.com/cisco-system-traffic-generator/trex-java-sdk/blob/693b0d69375c174c8bb166819fb289652b6437da/src/main/java/com/cisco/trex/stateless/model/VMInstruction.java#L3) without implementation.

It is a simple POJO so you can learn more about VM instructions from Python API or Stateless GUI. Try to create a profile with VM instructions in the GUI and save them. Then just open it in your favorite editor and you will see the proper structure of VM instructions.

**Comment by walrusss** [comment]
It works, Thanks.
