### ISSUE TITLE
Make jar available in a maven repository 

### ISSUE THREAD

**Issue by Elisedlund** [cisco-system-traffic-generator/trex-java-sdk#7]
I couldn't find this library deployed to any remote repository like maven central: http://central.maven.org/maven2/

Example: https://mvnrepository.com/search?q=trex-java-sdk
while other trex libraries do exist:  https://mvnrepository.com/search?q=trex

What I would like to achieve is to use this library simply by including it in my maven pom file or my gradle file and avoid building an jar myself

(Am I just stupid who are not able to find it? )

**Comment by hedjuo** [comment]
Hello.

We didn't upload any trex-java-sdk JARs to maven central yet.

**Comment by pillerthriller** [comment]
Do you plan on doing that?
Would make it much easier to use, now i have to create the jar myself and add to my project.

**Comment by kisel** [comment]
Hello, we have this task in our backlog, but didn't scheduled it yet, as there are other easy ways to use the module. Do you think https://jitpack.io/ works for you?

At this moment we've used it for stateless-gui to build and include trex-packet-editor and trex-java-sdk components.

Examples:
https://github.com/cisco-system-traffic-generator/trex-stateless-gui/blob/master/pom.xml#L42
https://github.com/cisco-system-traffic-generator/trex-stateless-gui/blob/master/pom.xml#L98

**Comment by pillerthriller** [comment]
Hi, locally it is working but im not sure it will work in all CI flows we use. But it is a start, thanks.

**Comment by pillerthriller** [comment]
Hi, is it released in maven central now or why was this closed?

**Comment by hedjuo** [comment]
No, I guess not. I thought the latest comment from @kisel resolved your issue.

**Comment by leomaatEric** [comment]
The latest release of version 1.28 has been deployed on central maven repo at:
https://repo1.maven.org/maven2/com/cisco/trex/trex-java-sdk/1.28/

this issue can be closed.
