### ISSUE TITLE
stop traffic does not contain field 'handler'

### ISSUE THREAD

**Issue by pillerthriller** [cisco-system-traffic-generator/trex-java-sdk#9]
when i use the TrexClient method stopTraffic(int portIndex) i get JSON error respons from server(v2.29): 
INFO : Call stop_traffic method.
INFO : JSON Req: {"method":"stop_traffic","id":"aggogxls","jsonrpc":"2.0","params":{"api_h":"Ptr5c4Rb","port_id":1}}
INFO : JSON Resp: [{"error":{"code":-32602,"message":"Bad paramters for method","specific_err":"field 'handler' is missing"},"id":"aggogxls","jsonrpc":"2.0"}]

Have i done something wrong or have something changed in recent version of trex or sdk?

**Comment by imarom** [comment]
please take a look at the spec:

[](https://trex-tgn.cisco.com/trex/doc/trex_rpc_server_spec.html#_stop_traffic)

any command which requires ownership should be provided with a handler.

**Comment by pillerthriller** [comment]
so why doesnt the sdk include the handler when it sends the command? can i do something different?

**Comment by pillerthriller** [comment]
i just saw that it looks like it sends the "stop traffic" call twice, one with handler and one without, i guess it it because of backwards compatibilty? maybe i should just ignore the second one that give the error response?

**Comment by hhaim** [comment]
You can use the our  Console with verbose mode enabled to explore  the RPC commands (of course the spec is good too)
There is no need for two stop commands.


Thanks,
Hanoh

**Comment by pillerthriller** [comment]
sorry, i found the reason.
I add traffic on one port and start it, but when i stop the traffic i call stop for both ports, the port that i havent started traffic on will be called without the handler.
Thanks for you help
